kind: pipeline
type: kubernetes
name: json-to-db

steps:
- name: download
  image: node:lts
  commands:
  - yarn
  - yarn start
- name: clone dir3-to-db repo
  image: alpine/git
  commands:
  - git clone https://github.com/doncicuto/dir3-to-db
  - ls /drone/src
