kind: pipeline
type: docker
name: download-json

steps:
- name: download
  image: node:lts
  volumes:
  - name: output
    path: /drone/src/.git/dist/output
  commands:
  - yarn
  - yarn start

volumes:
- name: output
  host:
    path: /tmp/dir3-json
